const KEY='korean60_state_v8',SECTIONS=['learn','flash','trace','write','quiz','review'];
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
let state=load(),view='home',dayId=firstOpen(),flash=0,flip=false,traceIndex=0,strokeIndex=0,accepted=[],path=[],down=false,quiz=null,timer=3600,timerHandle=null,koVoice=null;
function load(){let s={doneDays:[],sections:{},mistakes:[],dates:[]};try{Object.assign(s,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){};try{let old=JSON.parse(localStorage.getItem('k60done')||'[]');if(Array.isArray(old)&&old.length>=6&&!s.doneDays.includes(1)){s.doneDays.push(1);s.sections['1']=[...SECTIONS]}}catch(e){};s.doneDays=[...new Set(s.doneDays||[])].sort((a,b)=>a-b);s.sections=s.sections||{};s.mistakes=s.mistakes||[];s.dates=s.dates||[];return s}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function lesson(id=dayId){return LESSONS[id-1]}
function firstOpen(){for(let i=1;i<=30;i++)if(!state.doneDays.includes(i)&&(i===1||state.doneDays.includes(i-1)))return i;return 30}
function unlocked(id){return id===1||state.doneDays.includes(id)||state.doneDays.includes(id-1)}
function secSet(){return new Set(state.sections[String(dayId)]||[])}
function study(){let k=new Date().toLocaleDateString('en-CA');if(!state.dates.includes(k)){state.dates.push(k);save()}}
function streak(){let set=new Set(state.dates),d=new Date(),n=0;d.setHours(0,0,0,0);for(let i=0;i<365;i++){let k=d.toLocaleDateString('en-CA');if(set.has(k)){n++;d.setDate(d.getDate()-1)}else if(i===0)d.setDate(d.getDate()-1);else break}return n}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function render(){view==='lesson'?renderLesson():view==='review'?renderMistakes():renderHome();$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===(view==='lesson'?'home':view)))}
function renderHome(){dayId=firstOpen();let p=Math.round(state.doneDays.length/30*100);$('#app').innerHTML=`<header class="top"><b>🇰🇷 KOREAN 60</b><button class="icon" id="help">?</button></header><section class="hero"><div class="hero-line"><div><small>LỘ TRÌNH 30 NGÀY · 60 PHÚT/NGÀY</small><h1>Tiếng Hàn từ số 0</h1><p>Tự lưu tiến độ · nghe · viết · quiz · ôn sai</p></div><div class="streak">🔥 ${streak()}</div></div><div class="progress"><i style="width:${p}%"></i></div><div class="stats"><div><b>${state.doneDays.length}/30</b><span>Ngày xong</span></div><div><b>${p}%</b><span>Tiến độ</span></div><div><b>${state.mistakes.length}</b><span>Cần ôn</span></div></div></section><button class="primary" id="continue">▶ Học tiếp · Ngày ${dayId}: ${esc(lesson().title)}</button><div class="note">✅ Hoàn thành bài trước sẽ tự mở bài sau. Bài đã học luôn mở để ôn. Tiến độ cũ của Ngày 1 được tự nhận diện.</div><section class="card"><div class="title"><b>Lộ trình 30 ngày</b><span class="pill">${state.doneDays.length} xong</span></div><div class="days">${LESSONS.map(d=>`<button class="day ${state.doneDays.includes(d.id)?'done':unlocked(d.id)?'open':'locked'}" data-day="${d.id}"><em>${state.doneDays.includes(d.id)?'✅':unlocked(d.id)?'▶':'🔒'}</em><small>NGÀY ${d.id}</small><b>${esc(d.title)}</b><span>${esc(d.goal)}</span></button>`).join('')}</div></section>`;$('#continue').onclick=()=>openDay(dayId);$$('.day').forEach(b=>b.onclick=()=>unlocked(+b.dataset.day)?openDay(+b.dataset.day):toast('🔒 Học xong Ngày '+(+b.dataset.day-1)+' trước'));$('#help').onclick=help}
function openDay(id){if(!unlocked(id))return toast('Bài chưa mở');dayId=id;flash=0;flip=false;traceIndex=0;strokeIndex=0;accepted=[];study();view='lesson';scrollTo(0,0);render()}
function doneBtn(id){return `<button class="doneBtn ${secSet().has(id)?'on':''}" data-sec="${id}">✓ Xong</button>`}
function renderLesson(){let d=lesson(),n=secSet().size;$('#app').innerHTML=`<header class="lessonTop"><button class="icon" id="back">←</button><div><small>NGÀY ${d.id} · ${n}/6 PHẦN</small><h1>${esc(d.title)}</h1><p>${esc(d.goal)}</p></div></header><section class="card"><div class="title"><b>⏱ Buổi học 60 phút</b><span class="pill ${n===6?'green':''}">${n}/6</span></div><div class="timer"><b id="clock">${fmt(timer)}</b><button id="timerBtn">${timerHandle?'Tạm dừng':'Bắt đầu'}</button><button id="timerReset">Đặt lại</button></div><div class="segments">${SECTIONS.map((_,i)=>`<i class="${i<n?'on':''}"></i>`).join('')}</div></section>${block('1. Học mới · 10 phút','learn',`<div class="letters">${d.cards.map((c,i)=>`<button data-card="${i}" class="letter"><b>${esc(c[0])}</b><span>${esc(c[1])}</span><small>chạm để nghe 🔊</small></button>`).join('')}</div><div class="tip">💡 ${esc(TIPS[d.id]||'Nghe – đọc theo – lặp lại thành tiếng 3 lần.')}</div>`)}${block('2. Flashcard · 10 phút','flash',`<div class="flash" id="flash"></div><div class="controls"><button id="prev">←</button><button id="flip">Lật thẻ</button><button id="next">→</button></div><button class="secondary full" id="speakFlash">🔊 Nghe thẻ này</button>`)}${block('3. Luyện viết · 15 phút','trace',`<div class="toolbar"><select id="traceSel">${d.trace.map((x,i)=>`<option value="${i}">${esc(x)}</option>`).join('')}</select><button id="redo">Làm lại</button></div><div class="strokeLine"><span class="pill" id="strokeBadge">Nét 1</span><button class="secondary" id="showStroke">▶ Xem nét</button></div><div class="canvas"><canvas id="traceCanvas" width="700" height="700"></canvas></div><div id="traceMsg" class="traceMsg"></div><div id="strokeInfo" class="tip"></div>`)}${block('4. Viết tự do · 10 phút','write',`<div class="toolbar"><button id="clearFree">Xóa bảng</button><button id="speakTarget">🔊 Nghe mẫu</button></div><div class="canvas free"><canvas id="freeCanvas" width="700" height="500"></canvas></div>`)}${block('5. Quiz nhanh · 10 phút','quiz',`<div id="question" class="question"></div><div id="answers" class="answers"></div><div id="quizMsg" class="quizMsg"></div><button class="primary" id="newQuiz">Câu tiếp</button>`)}${block('6. Ôn lại · 5 phút','review',`<div class="reviewText">${esc(REVIEW[d.id]||d.cards.slice(0,6).map(c=>c[0]+' = '+c[1]).join(' · '))}</div><div class="note">Đánh dấu đủ 6 phần để hoàn thành ngày. Từ trả lời sai sẽ tự vào mục “Ôn sai”.</div><button class="primary" id="finish">${state.doneDays.includes(d.id)?'✅ Đã hoàn thành · Về lộ trình':d.id<30?'Hoàn thành ngày '+d.id+' → Mở ngày '+(d.id+1):'🏆 Hoàn thành khóa 30 ngày'}</button>`)} `;bindLesson()}
function block(title,id,body){return `<section class="card"><div class="title"><b>${title}</b>${doneBtn(id)}</div>${body}</section>`}
function bindLesson(){let d=lesson();$('#back').onclick=()=>{view='home';render();scrollTo(0,0)};$$('.doneBtn').forEach(b=>b.onclick=()=>{let s=secSet(),id=b.dataset.sec;s.has(id)?s.delete(id):s.add(id);state.sections[String(dayId)]=[...s];save();renderLesson()});$$('.letter').forEach(b=>b.onclick=()=>{let c=d.cards[+b.dataset.card];speak(c[2]||c[0],c[0]+' · '+c[1])});$('#prev').onclick=()=>{flash=(flash+d.cards.length-1)%d.cards.length;flip=false;drawFlash()};$('#next').onclick=()=>{flash=(flash+1)%d.cards.length;flip=false;drawFlash()};$('#flip').onclick=$('#flash').onclick=()=>{flip=!flip;drawFlash()};$('#speakFlash').onclick=()=>speak(d.cards[flash][2]||d.cards[flash][0],d.cards[flash][0]);drawFlash();$('#traceSel').value=traceIndex;$('#traceSel').onchange=e=>{traceIndex=+e.target.value;strokeIndex=0;accepted=[];drawTrace()};$('#redo').onclick=()=>{strokeIndex=0;accepted=[];$('#traceMsg').textContent='';drawTrace()};setupTrace();drawTrace();$('#showStroke').onclick=animateStroke;setupFree();$('#clearFree').onclick=clearFree;$('#speakTarget').onclick=()=>speak(d.trace[traceIndex]||d.cards[0][2],d.trace[traceIndex]);newQuiz();$('#newQuiz').onclick=newQuiz;$('#finish').onclick=finishDay;$('#timerBtn').onclick=toggleTimer;$('#timerReset').onclick=()=>{stopTimer();timer=3600;updateClock()}}
function drawFlash(){let c=lesson().cards[flash],e=$('#flash');e.classList.toggle('back',flip);e.innerHTML=flip?`<div><b>${esc(c[1])}</b><small>${esc(c[2]||c[0])}</small></div>`:esc(c[0])}
function loadVoices(){if(!('speechSynthesis'in window))return;koVoice=speechSynthesis.getVoices().find(v=>String(v.lang).toLowerCase().startsWith('ko'))||null}loadVoices();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=loadVoices;
function speak(text,label){if(!('speechSynthesis'in window))return toast('Máy chưa hỗ trợ phát âm');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';if(koVoice)u.voice=koVoice;u.rate=.72;speechSynthesis.speak(u);toast('🔊 '+label)}
function guide(t){if(STROKES[t])return STROKES[t];if(COMPOUND[t])return COMPOUND[t].flatMap(x=>STROKES[x]||[]);return null}
function target(){return lesson().trace[traceIndex]||''}
function grid(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,w,h);ctx.save();ctx.strokeStyle='#dbe3ef';ctx.lineWidth=2;ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(w/2,15);ctx.lineTo(w/2,h-15);ctx.stroke();ctx.beginPath();ctx.moveTo(15,h/2);ctx.lineTo(w-15,h/2);ctx.stroke();ctx.restore()}
function setupTrace(){let c=$('#traceCanvas');const pos=e=>{let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*700/r.width,y:(e.clientY-r.top)*700/r.height}};c.onpointerdown=e=>{down=true;path=[pos(e)];try{c.setPointerCapture(e.pointerId)}catch(_){}};c.onpointermove=e=>{if(!down)return;path.push(pos(e));drawTrace(true)};c.onpointerup=()=>{if(!down)return;down=false;grade()};c.onpointercancel=()=>down=false}
function drawTrace(active=false){let c=$('#traceCanvas'),ctx=c.getContext('2d'),t=target(),g=guide(t);grid(ctx,700,700);ctx.fillStyle='#cbd5e1';ctx.font=`bold ${t.length>3?120:t.length>1?210:400}px -apple-system,"Apple SD Gothic Neo",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t,350,370);if(g)g.forEach((s,i)=>drawGuide(ctx,s,i,i<strokeIndex?1:i===strokeIndex?.95:.22));accepted.forEach(p=>drawPath(ctx,p,'#16a34a'));if(active&&path.length>1)drawPath(ctx,path,'#111827');let b=$('#strokeBadge'),info=$('#strokeInfo');if(g){b.textContent=strokeIndex>=g.length?'✓ Đủ nét':`Nét ${strokeIndex+1}/${g.length}`;info.innerHTML=`<b>Thứ tự nét ${esc(t)}</b><br>${g.map((_,i)=>`${i+1}. Bắt đầu ở chấm ${i+1}, kéo theo mũi tên.`).join('<br>')}`}else{b.textContent='Viết theo mẫu';info.innerHTML=`<b>${esc(t)}</b><br>Đây là khối/từ. Viết theo chữ mờ; sơ đồ nét chi tiết tập trung ở các ngày học bảng chữ cái.`}}
function drawGuide(ctx,s,i,a){let p=s.map(x=>({x:x[0]*700,y:x[1]*700}));ctx.save();ctx.globalAlpha=a;ctx.strokeStyle=i<strokeIndex?'#22c55e':'#ff7a18';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=10;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);p.slice(1).forEach(x=>ctx.lineTo(x.x,x.y));ctx.stroke();let st=p[0];ctx.beginPath();ctx.arc(st.x,st.y,25,0,Math.PI*2);ctx.fill();ctx.fillStyle='white';ctx.font='bold 24px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(i+1,st.x,st.y+1);let x=p[p.length-2],y=p[p.length-1],ang=Math.atan2(y.y-x.y,y.x-x.x),l=28;ctx.fillStyle=i<strokeIndex?'#22c55e':'#ff7a18';ctx.beginPath();ctx.moveTo(y.x,y.y);ctx.lineTo(y.x-l*Math.cos(ang-.5),y.y-l*Math.sin(ang-.5));ctx.lineTo(y.x-l*Math.cos(ang+.5),y.y-l*Math.sin(ang+.5));ctx.closePath();ctx.fill();ctx.restore()}
function drawPath(ctx,p,color){if(p.length<2)return;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=18;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);p.slice(1).forEach(x=>ctx.lineTo(x.x,x.y));ctx.stroke();ctx.restore()}
const pd=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);function ds(p,a,b){let x=b.x-a.x,y=b.y-a.y,l=x*x+y*y;if(!l)return pd(p,a);let t=Math.max(0,Math.min(1,((p.x-a.x)*x+(p.y-a.y)*y)/l));return Math.hypot(p.x-a.x-t*x,p.y-a.y-t*y)}function poly(p,pts){let m=1e9;for(let i=1;i<pts.length;i++)m=Math.min(m,ds(p,pts[i-1],pts[i]));return m}
function grade(){let g=guide(target()),m=$('#traceMsg');if(!g){accepted.push([...path]);path=[];drawTrace();m.className='traceMsg good';m.textContent='✓ Đã ghi nét. Tiếp tục viết theo mẫu.';return}if(strokeIndex>=g.length){path=[];drawTrace();return}if(path.length<2)return;let ex=g[strokeIndex].map(x=>({x:x[0]*700,y:x[1]*700})),sample=path.filter((_,i)=>i%Math.max(1,Math.floor(path.length/20))===0),avg=sample.reduce((s,p)=>s+poly(p,ex),0)/sample.length;if(pd(path[0],ex[0])<110&&pd(path.at(-1),ex.at(-1))<130&&avg<95){accepted.push([...path]);strokeIndex++;m.className='traceMsg good';m.textContent=strokeIndex>=g.length?'✓ Đúng! Hoàn thành '+target():'✓ Đúng nét. Sang nét '+(strokeIndex+1);if(strokeIndex>=g.length)speak(target(),target())}else{m.className='traceMsg bad';m.textContent='Chưa đúng hướng. Bắt đầu ở chấm '+(strokeIndex+1)+' rồi kéo theo mũi tên.'}path=[];drawTrace()}
function animateStroke(){let g=guide(target());if(!g)return toast('Từ này không có sơ đồ từng nét');let s=g[Math.min(strokeIndex,g.length-1)].map(x=>({x:x[0]*700,y:x[1]*700})),st=performance.now();function f(now){drawTrace();let q=Math.min(1,(now-st)/900),seg=s.length-1,t=q*seg,i=Math.min(seg-1,Math.floor(t)),fr=t-i,p=s.slice(0,i+1),a=s[i],b=s[i+1];if(b)p.push({x:a.x+(b.x-a.x)*fr,y:a.y+(b.y-a.y)*fr});drawPath($('#traceCanvas').getContext('2d'),p,'#2563eb');if(q<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
function setupFree(){let c=$('#freeCanvas'),ctx=c.getContext('2d');clearFree();let d=false,last;const pos=e=>{let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*700/r.width,y:(e.clientY-r.top)*500/r.height}};c.onpointerdown=e=>{d=true;last=pos(e);try{c.setPointerCapture(e.pointerId)}catch(_){}};c.onpointermove=e=>{if(!d)return;let p=pos(e);ctx.strokeStyle='#0f172a';ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};c.onpointerup=()=>d=false;c.onpointercancel=()=>d=false}
function clearFree(){let c=$('#freeCanvas');if(c)grid(c.getContext('2d'),700,500)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function pool(mode,ans){let a=[];for(let d of LESSONS.slice(0,Math.max(dayId,6)))for(let c of d.cards)a.push(mode==='meaning'?c[1]:c[0]);return [...new Set(a)].filter(x=>x!==ans)}
function newQuiz(){let d=lesson(),c=d.cards[Math.floor(Math.random()*d.cards.length)],mode=Math.random()<.5?'meaning':'front',ans=mode==='meaning'?c[1]:c[0],q=mode==='meaning'?`“${c[0]}” nghĩa/đọc là gì?`:`Chọn tiếng Hàn cho “${c[1]}”`,opts=shuffle([ans,...shuffle(pool(mode,ans)).slice(0,3)]);quiz={c,ans,opts,answered:false};$('#question').textContent=q;$('#answers').innerHTML=opts.map((x,i)=>`<button data-a="${i}">${esc(x)}</button>`).join('');$('#quizMsg').textContent='';$$('#answers button').forEach(b=>b.onclick=()=>answer(+b.dataset.a))}
function answer(i){if(quiz.answered)return;quiz.answered=true;let pick=quiz.opts[i],ok=pick===quiz.ans;$$('#answers button').forEach((b,j)=>{if(quiz.opts[j]===quiz.ans)b.classList.add('ok');else if(j===i)b.classList.add('no')});let m=$('#quizMsg');m.className='quizMsg '+(ok?'good':'bad');m.textContent=ok?'✓ Chính xác':'✗ Đáp án đúng: '+quiz.ans;if(ok)speak(quiz.c[2]||quiz.c[0],quiz.c[0]);else{let key=dayId+'|'+quiz.c[0];if(!state.mistakes.some(x=>x.key===key))state.mistakes.push({key,day:dayId,front:quiz.c[0],back:quiz.c[1],speak:quiz.c[2]||quiz.c[0]});save()}}
function finishDay(){let d=lesson();if(state.doneDays.includes(d.id)){view='home';render();scrollTo(0,0);return}let s=secSet();if(s.size<6)return toast('Còn '+(6-s.size)+' phần chưa đánh dấu Xong');state.doneDays.push(d.id);state.doneDays=[...new Set(state.doneDays)].sort((a,b)=>a-b);study();save();stopTimer();timer=3600;if(d.id<30){toast('🎉 Đã mở Ngày '+(d.id+1));setTimeout(()=>openDay(d.id+1),600)}else{toast('🏆 Hoàn thành khóa 30 ngày!');view='home';render();scrollTo(0,0)}}
function renderMistakes(){let m=state.mistakes;$('#app').innerHTML=`<header class="top"><div><small>🧠 ÔN SAI</small><h1>Các từ bạn từng trả lời sai</h1><p>Chạm thẻ để nghe lại.</p></div></header><section class="card">${m.length?`<div class="letters">${m.map((x,i)=>`<button class="letter mistake" data-i="${i}"><b>${esc(x.front)}</b><span>${esc(x.back)}</span><small>🔊 nghe</small></button>`).join('')}</div><button class="danger full" id="clearMistakes">Xóa danh sách ôn sai</button>`:`<div class="reviewText">🎉 Chưa có từ sai cần ôn. Cứ học tiếp.</div>`}</section>`;$$('.mistake').forEach(b=>b.onclick=()=>{let x=m[+b.dataset.i];speak(x.speak,x.front+' · '+x.back)});if($('#clearMistakes'))$('#clearMistakes').onclick=()=>{if(confirm('Xóa toàn bộ danh sách ôn sai?')){state.mistakes=[];save();renderMistakes()}}}
function help(){sheet(`<h2>📱 Cách dùng</h2><div class="reviewText">1. Bấm <b>Học tiếp</b>.<br>2. Chạm chữ để nghe phát âm.<br>3. Luyện viết: bắt đầu ở chấm số 1 và kéo theo mũi tên.<br>4. Đánh dấu đủ 6 phần rồi bấm <b>Hoàn thành ngày</b>.<br>5. App tự mở ngày tiếp theo và tự lưu tiến độ.</div><div class="note">Trên iPhone: Safari → Chia sẻ → Thêm vào Màn hình chính.</div><button class="primary" onclick="closeSheet()">Đã hiểu</button>`)}
function settings(){sheet(`<h2>⚙️ Cài đặt</h2><p>Tiến độ lưu ngay trên iPhone/trình duyệt.</p><button class="secondary full" id="copyState">Sao chép bản sao tiến độ</button><button class="danger full" id="resetState">Xóa toàn bộ tiến độ</button><button class="secondary full" onclick="closeSheet()">Đóng</button>`);$('#copyState').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(state));toast('Đã sao chép tiến độ')}catch(e){toast('Trình duyệt không cho sao chép')}};$('#resetState').onclick=()=>{if(confirm('Xóa toàn bộ tiến độ 30 ngày?')){localStorage.removeItem(KEY);localStorage.removeItem('k60done');state=load();closeSheet();view='home';render();toast('Đã đặt lại tiến độ')}}}
function sheet(html){$('#sheet').innerHTML=html;$('#modal').classList.add('show')}window.closeSheet=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')closeSheet()}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function updateClock(){if($('#clock'))$('#clock').textContent=fmt(timer)}function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}function toggleTimer(){if(timerHandle){stopTimer();$('#timerBtn').textContent='Tiếp tục'}else{timerHandle=setInterval(()=>{timer=Math.max(0,timer-1);updateClock();if(!timer){stopTimer();toast('⏱ Hết 60 phút. Làm phần ôn lại nhé!')}},1000);$('#timerBtn').textContent='Tạm dừng'}}
$$('.nav button').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='settings')return settings();view=b.dataset.nav;render();scrollTo(0,0)});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();